import 'echarts/theme/bee-inspired'
import 'echarts/theme/blue'
import 'echarts/theme/caravan'
import 'echarts/theme/carp'
import 'echarts/theme/forest'
import 'echarts/theme/dark-blue'
import 'echarts/theme/jazz'
import 'echarts/theme/fruit'
import 'echarts/theme/london'
import 'echarts/theme/red'
import 'echarts/theme/vintage'
import 'echarts/theme/tech-blue'
import 'echarts/theme/sakura'
import 'echarts/theme/shine'
import 'echarts/theme/helianthus'
import 'echarts/theme/roma'
import 'echarts/theme/royal'
import 'echarts/theme/macarons'
import 'echarts/theme/macarons2'
import 'echarts/theme/inspired'
import 'echarts/theme/infographic'
import 'echarts/theme/green'
import 'echarts/theme/dark-mushroom'
import echarts from 'echarts'
import china from 'echarts/map/json/china.json'
import cities from 'echarts/map/json/china-cities.json'
import contour from 'echarts/map/json/china-contour.json'
import world from 'echarts/map/json/world.json'
echarts.registerMap('china', china)
echarts.registerMap('my', cities)
echarts.registerMap('contour', contour)
echarts.registerMap('world', world)
